apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arm64v8-pocketcoind.fullname" . }}
  labels:
    {{- include "arm64v8-pocketcoind.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "arm64v8-pocketcoind.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "arm64v8-pocketcoind.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arm64v8-pocketcoind.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["/home/pocketcoin/init.sh"]
          envFrom:
            - secretRef:
                name: pocketcoind-rpc-creds
          {{- with .Values.initEnv }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.persistence.mounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.persistence.mounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.image.lifecycle }}
          lifecycle: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.persistence.volumes }}
      volumes: {{- toYaml . | nindent 6 }}
      {{- end }}
