apiVersion: v1
kind: Service
metadata:
  name: {{ include "arm64v8-pocketcoind.fullname" . }}
  labels:
    {{- include "arm64v8-pocketcoind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "arm64v8-pocketcoind.selectorLabels" . | nindent 4 }}
